on: [push, pull_request]

name: tests

jobs:
  checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        tc: [1.85.0, stable, beta, nightly]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.tc }}
        components: rustfmt, clippy
        override: true
    - run: cargo fmt --check
    - run: cargo clippy -- -D warnings
    - run: cargo clippy --all-features -- -D warnings
    - run: cargo doc
    - run: cargo test --all --all-features
  checks-cross-compile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        tc: [1.85.0, stable, beta, nightly]
        cc:
        - aarch64-linux-android
        - i686-pc-windows-gnu
        - i686-unknown-freebsd
        - i686-unknown-linux-gnu
        - wasm32-wasip1
        - wasm32-unknown-unknown
        - x86_64-apple-darwin
        - x86_64-unknown-redox
        - x86_64-unknown-illumos
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.tc }}
        target: ${{ matrix.cc }}
        components: clippy
        override: true
    - run: cargo clippy --target=${{ matrix.cc }} -- -D warnings
    - run: cargo clippy --all-features --target=${{ matrix.cc }} -- -D warnings
    - run: cargo build --all-features --target=${{ matrix.cc }}
  checks-cross-compile-ios:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        tc: [1.85.0, stable, beta, nightly]
        cc: [aarch64-apple-ios]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.tc }}
        target: ${{ matrix.cc }}
        components: clippy
        override: true
    - run: cargo clippy --target=${{ matrix.cc }} -- -D warnings
    - run: cargo clippy --all-features --target=${{ matrix.cc }} -- -D warnings
    - run: cargo build --all-features --target=${{ matrix.cc }}
